---
- hosts: all
  remote_user: root
  tasks:
  - name: install nginx, php-fpm and php-cli on the latest version
    apt: 
      package: ['nginx', 'php-fpm', 'php-cli', 'python3-apt']
      update_cache: yes
      state: latest

  - name: remove apache2 package
    apt:
      package: apache2
      state: absent

  - name: get port, default 22
    delegate_to: localhost
    set_fact:
      ansible_ssh_port: "{{ hostvars[inventory_hostname]['ansible_ssh_port'] | default('22') }}"

  - name: ensure ssh host key known
    delegate_to: localhost
    lineinfile:
      dest: ~/.ssh/known_hosts
      create: yes
      state: present
      line: "{{ lookup('pipe', 'ssh-keyscan -trsa -p' + ansible_ssh_port + ' ' + inventory_hostname) }}"

  - name: update apt repo and cache on all debian/ubuntu boxes
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

  - name: upgrade all packages on servers
    apt: upgrade=dist force_apt_get=yes

  - name: check if a reboot is needed on all servers
    register: reboot_required_file
    stat: path=/var/run/reboot-required get_md5=no

  - name: reboot the box if kernel updated
    reboot:
      msg: "Reboot initiated by Ansible for kernel updates"
      connect_timeout: 5
      reboot_timeout: 300
      pre_reboot_delay: 0
      post_reboot_delay: 30
      test_command: uptime
    when: reboot_required_file.stat.exists