---
- name: clone the code repository to the docroot
  git:
    repo: "{{ item.git }}"
    dest: /var/www/{{ item.domain }}
    accept_hostkey: yes
    key_file: /home/{{ nginx_user }}/.ssh/id_rsa
  become_user: "{{ nginx_user }}"
  with_items: "{{ domains }}"
  when: item.git != false

- name: start nginx and php-fpm
  service:
    name: "{{ item }}"
    state: restarted
  with_items:
    - nginx
    - php{{ php_version.stdout }}-fpm

- name: create /usr/local/bin/updaterepos.sh
  template: 
    src: templates/updaterepos.sh.j2
    dest: /usr/local/bin/updaterepos.sh
    owner: "{{ nginx_user }}"
    group: "{{ nginx_user }}"
    mode: '0755'

- name: create cron job to auto pull repos every 15 minutes
  cron:
    user: "{{ nginx_user }}"
    name: "automatic update repos"
    # special_time: hourly
    minute: "*/15"
    job: "/usr/local/bin/updaterepos.sh 2>&1"