---
- name: get php version
  shell: >
    php -r "echo substr(phpversion(),0,3);"
  changed_when: false
  register: php_version

- name: remove default nginx config
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "/etc/nginx/nginx.conf"
    - "/etc/nginx/sites-enabled/default"
    - "/etc/nginx/sites-available/default"
    - "/etc/nginx/sites-available/{{ default_domain }}.conf"
    - "/etc/nginx/sites-enabled/{{ default_domain }}.conf"

- name: setup nginx.conf
  template: 
    src: templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf

- name: setup default site
  template: 
    src: templates/default.j2
    dest: /etc/nginx/sites-available/{{ default_domain }}.conf

- name: create symlink for default site
  file: 
    src: /etc/nginx/sites-available/{{ default_domain }}.conf
    dest: /etc/nginx/sites-enabled/{{ default_domain }}.conf
    state: link

- name: setup vhost for each item
  template: 
    src: templates/sites.j2
    dest: /etc/nginx/sites-available/{{ item }}.conf
  with_items: "{{ domains }}"

- name: create symlinks for sites-enabled
  file: 
    src: /etc/nginx/sites-available/{{ item }}.conf
    dest: /etc/nginx/sites-enabled/{{ item }}.conf
    state: link
  with_items: "{{ domains }}"
  notify:
    - reload nginx

- name: creates /var/www/sites directory
  file:
    path: /var/www/{{ item }}
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'
  with_items: "{{ domains }}"

- name: install index.php for all sites
  template: 
    src: templates/index.php.j2
    dest: /var/www/{{ item }}/index.php
    owner: www-data
    group: www-data
    mode: '0644'
  with_items: "{{ domains }}"
  when: item != 'html'

- name: install index.php for default site
  template: 
    src: templates/index.default.php.j2
    dest: /var/www/html/index.php
    owner: www-data
    group: www-data
    mode: '0644'

- name: list dirs in /var/www/  
  command: ls /var/www
  register: www_folders

- name: create info.php for every folder on /var/www/
  copy:
    content: '<?php phpinfo(); ?>'
    dest: "/var/www/{{ item }}/info.php"
  with_items: "{{ www_folders.stdout_lines }}"

- name: start nginx and php-fpm
  service:
    name: "{{ item }}"
    state: restarted
  with_items:
    - nginx
    - php{{ php_version.stdout }}-fpm
