---
- name: remove apache2 package
  apt:
    name: apache2
    state: absent

- name: install nginx, php-fpm and php-cli on the latest version
  apt: 
    package: ['nginx', 'php-fpm', 'php-cli']
    state: latest

- name: get php version
  shell: >
    php -r "echo substr(phpversion(),0,3);"
  changed_when: false
  register: php_version

- name: remove default nginx config
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "/etc/nginx/nginx.conf"
    - "/etc/nginx/sites-enabled/default"
    - "/etc/nginx/sites-available/default"

- name: setup nginx.conf
  template: 
    src: templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf

- name: setup default site
  template: 
    src: templates/default.j2
    dest: /etc/nginx/sites-available/default

- name: setup vhost for {{ item }}
  template: 
    src: templates/sites.j2
    dest: /etc/nginx/sites-available/{{ item }}.conf
  with_items: "{{ domains }}"

- name: create symlinks for sites-enabled
  file: state=link src=/etc/nginx/sites-available/{{ item }}.conf dest=/etc/nginx/sites-enabled/{{ item }}.conf
  with_items: "{{ domains }}"
  notify:
    - reload nginx

- name: creates /var/www/sites directory
  file:
    path: /var/www/{{ item }}
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'
  with_items: "{{ domains }}"

- name: install index.php
  template: 
    src: templates/index.php.j2
    dest: /var/www/{{ item }}/index.php
  with_items: "{{ domains }}"

- name: list dirs in /var/www/  
  command: ls /var/www
  register: www_folders

- name: create info.php for every folder on /var/www/
  copy:
    content: '<?php phpinfo(); ?>'
    dest: "/var/www/{{ item }}/info.php"
  with_items: "{{ www_folders.stdout_lines }}"

- name: start nginx and php-fpm
  service:
    name: "{{ item }}"
    state: started
  with_items:
    - nginx
    - php-fpm
